# Configuration for Compose, see https://detekt.dev/docs/introduction/compose/
naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  LongMethod:
    threshold: 80
  TooManyFunctions:
    ignoreAnnotatedFunctions: [ 'Preview' ]
    thresholdInClasses: 15


style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  MaxLineLength:
    excludes: [ '**/test/**', '**/*.Test.kt' ]
