name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Chrckout repo
        uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test and Build
        run: ./gradlew build

      - name: Generate Code-Coverage report
        run: ./gradlew jacoco

      - name: Push Code-Coverage Report to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
