name: Android CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Screenshot Test
        env:
          SCREENSHOTBOT_API_KEY: ${{ secrets.SCREENSHOTBOT_API_KEY }}
          SCREENSHOTBOT_API_SECRET: ${{ secrets.SCREENSHOTBOT_API_SECRET }}
        run: ./gradlew recordAndVerifyDebugScreenshotTest

      - name: Build
        run: ./gradlew build

      - name: Generate Code-Coverage report
        run: ./gradlew createDebugUnitTestCoverageReport

      - name: Push Code-Coverage Report to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests/'

      - name: Upload Screenshot Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: screehnshot-test-reports
          path: '**/build/reports/screenshotTest/'

      - name: Upload Coverage Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: '**/build/reports/coverage/'

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: '**/build/outputs/apk/'
